### ISSUE TITLE
Browser cache issues with user login

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-login#264] opened 2020-09-10 17:30 UTC
I am not sure if my issue is related to some others, so I opened a new Bug.
`grav 1.6.26`
`login 3.3.5`

I am using the `php` command to host the website locally.

I've added the oauth2 plugin, to allow users to signin via github. I am at a **very** early stage, just trying things out. Logging in and logging out works, **but** when I change to another page, the user is still shown as logged in. The quark theme has an option to show the logged in user at the top, and he is still shown. If I press shift+reload (in firefox) the site is loaded properly. I've turned off cache for the site, and system wide.

How can that happen, and why does a browser full reload 'fix' the issue?

Edit:
I've noticed that the error happens
- [x] Firefox 80.0.1 (the one I am always using)
- [x] Developer Firefox (newly installed, no settings changed)
- [ ] Chromium (Everything works fine)
- [ ] Midori (Everything works fine)

I've also seen this issue before while working on some query parameters. Firefox seems to cache more aggressively, and does not invalidate websites. But is this really a firefox issue?

But how to debug this now?

### Steps to reproduce:
1. Use [Grav Quark Blog Skeleton](https://github.com/getgrav/grav-skeleton-blog-site)
2. Install oauth2 plugin `bin/gpm install login-oauth2`
3. Add github as authentication provider (client and secret id)
4. Start server with `php -S localhost:8000 system/router.php`
4. Go to your page `http://localhost:8000/login`
5. Login via github
6. Click the logout button
7. You will see, that the logout does not happen. Only if you either wait a few seconds or reload the page using shift + reload.

**Comment by NicoHood** [comment] 2020-09-11 10:42
This is a screenshot of the firefox network analysis. It shows a `pragma: no-cache` (which is probably respected by chrome, but not firefox) and the `cache-control: max-age=604800`.

![grafik](https://user-images.githubusercontent.com/6888294/92911556-4b287300-f429-11ea-94fc-227fdfc77855.png)

If I set the cache control to nocache, the site works properly. However it will always reload... and that is not the goal. Using `etag` also does not help. I am not sure if this is an issue of grav core or the login/oauth plugin itself. I've noticed similar issues with normal twig templates that did not change, even if I've edited them (with file cache turned off).
```yaml
pages:
  cache_control: 'no-cache'
```

**Comment by mahagr** [comment] 2020-09-11 11:36
Try something like this:

```
pages:
  expires: 3600
  cache_control: 'no-store, no-cache, must-revalidate'
  etag: true
```

**Comment by NicoHood** [comment] 2020-09-11 12:31
Thanks for helping me out!

The issue is fixed, but cache is not working anymore. The browser reloads the whole page. I'd expect a 304, but I always get a 200 on a page refresh:
![grafik](https://user-images.githubusercontent.com/6888294/92925795-5389a980-f43b-11ea-9d78-faa69895fe8b.png)

Correct me, if I am wrong.

The issue is very simple to reproduce with the provided steps, in case you need a minimal example to test yourself.

**Comment by NicoHood** [comment] 2020-09-11 16:14
Important update:
I've tried with Firefox 78 and the issue does not occur. **Firefox 80.0.1 has the issue.**(on Archlinux) But how should we proceed now?

**Comment by mahagr** [comment] 2020-09-11 17:19
I'm aware that this change was made in FF 80, but I think it's just good thing as it basically acts like you're behind caching proxy (which used to cause the same issue, but most people didn't notice it).

Try updating Grav to 1.7, it has some important improvements on 304 responses.

**Comment by NicoHood** [comment] 2020-09-11 20:29
Could you maybe go more into detail about what changed? It would be nice, to also solve this issue with grav 1.6 and this should be added to the readme. If the is an intended behavior, you will see more confused users soon.

The upgrade did not work for me:
```
Would you like to upgrade now? [y|N] y

Preparing to upgrade to v1.7.0-rc.16..
  |- Downloading upgrade [6.27M]...   100%
  |- Installing upgrade...    ok                             
  '- Success!  

PHP Fatal error:  Uncaught Error: Call to undefined method Grav\Common\Page\Pages::register() in /home/user/Documents/grav-skeleton-blog-site/system/src/Grav/Common/Processors/InitializeProcessor.php:326
Stack trace:
#0 /home/user/Documents/grav-skeleton-blog-site/system/src/Grav/Common/Processors/InitializeProcessor.php(139): Grav\Common\Processors\InitializeProcessor->initializePages()
#1 /home/user/Documents/grav-skeleton-blog-site/system/src/Grav/Common/Processors/InitializeProcessor.php(46): Grav\Common\Processors\InitializeProcessor->processCli()
#2 /home/user/Documents/grav-skeleton-blog-site/system/src/Grav/Console/ConsoleCommand.php(66): Grav\Common\Processors\InitializeProcessor::initializeCli()
#3 /home/user/Documents/grav-skeleton-blog-site/system/src/Grav/Console/ConsoleCommand.php(107): Grav\Console\ConsoleCommand->initializeGrav()
#4 /home/user/Documents/ in /home/user/Documents/Sport/BikeFitting/Haendler/grav-skeleton-blog-site/system/src/Grav/Common/Processors/InitializeProcessor.php on line 326
```

**Comment by rhukster** [comment] 2020-09-11 20:49
We'll continue to investigate this...

**Comment by mahagr** [comment] 2020-09-14 07:36
I'm able to reproduce this issue.

**Comment by mahagr** [comment] 2020-09-14 10:57
I fixed part of this, because of login/profile (and admin login) pages were also cached into the browser. Those have now been fixed as they should never be cached.

What is not fixed yet are the other pages with user/login information in them and login/access protected pages. 
Also CLI upgrade needs to be looked at.

**Comment by NicoHood** [comment] 2020-10-03 19:48
Did you manage to also fix the other pages?

**Comment by mahagr** [comment] 2020-10-05 17:17
We are still working on the fixes as we're finding more cases.

**Comment by NicoHood** [comment] 2020-10-25 12:06
I just noticed, that also the messaging system is affected.

I wrote a plugin that requires the user to click an activation link via email. If he already klicked on the link, a message will pop out. But the message will not be shown unless you reload the page. I am not yet sure if this requires a fix on grav itself, or if I can manually clear the cache for the user?

**Comment by NicoHood** [comment] 2020-10-25 19:10
It turns out, that the following setting works for me in the message scenario:
```yaml
  expires: 3600  
  cache_control: 'public, max-age=0, must-revalidate'
  etag: true
```
The setting was taken from [here](https://www.thepolyglotdeveloper.com/2019/09/test-etag-browser-caching-curl-requests/). I have little knowledge about this, maybe you can tell me more if that is correct. Also I am wondering if there should be a mechanism to set the **cache control to `private` for logged in users.**

**Comment by rhukster** [comment] 2020-10-26 17:23
@mahagr I think we should look into changing the cache_control for logged in users.. its something we could do from the login plugin.

**Comment by mahagr** [comment] 2020-10-27 12:00
Yes, I agree. Though that may not be enough as the pages which exist for the guests are still going to be an issue -- they will be cached for a week by default.

**Comment by NicoHood** [comment] 2020-10-27 19:35
Nice! So I guess we found the root issue, did we? I also aggree on @mahagr that existing pages will still be cached. Since grav (and its themes) are built with messaging enabled by default it would make sense to set the default header to:

```yaml
  expires: 3600
  cache_control: 'private, max-age=0, must-revalidate'
  etag: true
```

This would
* Still allow caching (etag is correctly used)
* Fix login plugin and messages caching issue
* Fix private information leak when a proxy is used (very important)

When this is **becomes a new default**, static pages or static websites (without any login or message function) could use a more aggressive caching at their own risk. This should be documented for grav, the login plugin and of course in the changelog, so people will understand better.

You recent changes to the login plugin maybe could be reverted then.

What I am not yet sure is the `expire` setting, if it would still matter whether it is set or not. I am also (not yet) an expert about the pragma cache settings.

**Comment by NicoHood** [comment] 2020-11-29 11:52
Is there a chance to make the cache setting suggested above the new default? I think this is **critical**, especially the `private` setting is currently not applied, meaning proxy server will leak private information when a user login is used. It basically does not make sense to enable the `session` by default, but not having `private` cache headers (and etag support off).

**Comment by mahagr** [comment] 2020-12-22 10:39
@NicoHood Now all the protected pages should have proper cache control. I made sure the pages can still be cached in the browser if ETag is enabled to speed up loading protected pages when they haven't been changed.

There is still an issue with system messages, which needs to be fixed elsewhere.

**Comment by mahagr** [comment] 2020-12-22 13:47
I'm closing this issue as the rest isn't related to login.

**Closed by mahagr** 2020-12-22 13:47 UTC
Labels: bug, fixed

**Comment by NicoHood** [comment] 2020-12-22 13:54
Where are the other issues tracked?

Wouldnt it still make sense to set some different default values? Or at least put a proper documentation/recommendation on cache strategies? I am wondering if fixing the cache works for messages etc. I am not yet sure what is a) the most common usecase and b) the best choice that does not break things

**Comment by mahagr** [comment] 2020-12-22 15:21
Session messages: https://github.com/getgrav/grav/issues/3108

I didn't create issue for forms, though.

I don't think that the default values need to be changed. For protected pages I am just forcing override for the Cache-Control as there's really no other way to prevent caching. It still allows you to set expire time, though.

**Comment by NicoHood** [comment] 2020-12-29 09:49
I guess this commit is now related:
https://github.com/getgrav/grav/commit/589c9e4445b64fbce7d399c78e5ed3902c95db3e
