### ISSUE TITLE
Nothing happens when registering

### ISSUE THREAD

**Issue by viion** [getgrav/grav-plugin-login#101] opened 2017-01-10 23:13 UTC
![screencapture-xivfc-dev-admin-plugins-login-1484090111276](https://cloud.githubusercontent.com/assets/270800/21828844/ad910634-d78a-11e6-8a45-cb70e35005d5.png)
Can't figure this one out.

I have the route `/accounts/register` setup, when I go there I see the registration form. I fill it in and click Submit, the page just reloads and does nothing, no error, no logs, nothing, just back onto an empty registration form.

Anything I'm missing on setup? User folder is writable, it works via CLI.

Running on Vagrant, Nginx 1.10, PHP 7.

Login config:
```yaml
enabled: true
built_in_css: false
route: /accounts/login
route_register: /accounts/register
route_activate: /activate_user
route_forgot: /forgot_password
route_reset: /reset_password
redirect_after_login: /
parent_acl: false
protect_protected_page_media: false
user_registration:
  enabled: true
  fields:
    - username
    - password
    - email
  access:
    site:
      login: 'true'
  options:
    validate_password1_and_password2: true
    set_user_disabled: false
    login_after_registration: false
    send_activation_email: false
    send_notification_email: false
    send_welcome_email: '0'
  redirect_after_registration: /accounts/register/complete
  redirect_after_activation: /
rememberme:
  enabled: true
  timeout: 604800
  name: grav-rememberme
```

**Comment by flaviocopes** [comment] 2017-01-11 13:58
I tried with this config and the Antimatter theme. I am redirected to `/accounts/register/complete` correctly. 

Tested on OSX MAMP and also with Caddy.

To find out if it's the web server setup, can you try with MAMP, which is known to work out of the box?

**Comment by viion** [comment] 2017-01-11 15:42
Hello,

Just tried it with Antimatter and the same issue. Tried with MAMP + Antimatter and same issue, could it be a setup issue? What would be the best way to debug it?

**Comment by flaviocopes** [comment] 2017-01-11 15:56
PM me your `user/` folder on Gitter, so I can try your same exact site

**Comment by flaviocopes** [comment] 2017-01-11 17:08
After a bit of debugging I found the problem is on sites that have no forms defined in their pages.

Adding a fake form to the home page 

```
---
title: Home

form:
    name: fake-form
---
```

makes the problem go away.

So the problem is replicated on sites with no forms defined.

**Comment by rhukster** [comment] 2017-04-14 02:24
Should be fixed in next release of forms plugin

**Closed by rhukster** 2017-04-14 02:24 UTC
