### ISSUE TITLE
visibility_requires_access corrupting frontmatter

### ISSUE THREAD

**Issue by no10staples** [getgrav/grav-plugin-login#255] opened 2020-06-05 02:31 UTC
If I am using
```
login:
    visibility_requires_access: true
```
in the frontmatter of a page, when I edit the page using the Admin interface, the login config gets inserted into the frontmatter. The workaround is to edit the page manually, but this appears to be a bug.
![56330197-05447e00-6155-11e9-8562-44090c0626b4](https://user-images.githubusercontent.com/36873341/83830435-79126300-a728-11ea-9c3d-59518daf973f.png)

**Comment by rhukster** [comment] 2020-06-05 10:48
What plugins do you have installed?

**Comment by no10staples** [comment] 2020-06-05 10:51
Hi Andy

[cid:image001.png@01D63B7B.111CBAC0]

Login-Ext is mine. It adds a couple of static functions and more access roles. Let me know if you need anything else.

Dan

**Comment by rhukster** [comment] 2020-06-05 10:53
Image broken ? Looks like you replied via email. Try via site.

**Comment by no10staples** [comment] 2020-06-05 10:58
![1](https://user-images.githubusercontent.com/36873341/83869077-52c3e600-a76f-11ea-86c3-69074019f4c9.png)

**Comment by rhukster** [comment] 2020-06-05 18:29
Duplicate of https://github.com/getgrav/grav-plugin-login/issues/228

fixed.

**Closed by rhukster** 2020-06-05 18:29 UTC
Labels: duplicate
