### ISSUE TITLE
Oauth creates users with faulty user rights

### ISSUE THREAD

**Issue by Ricoom** [getgrav/grav-plugin-login#54] opened 2016-02-04 08:16 UTC
Correct working user rights on user.yaml are 
access:
`access:`
`    site:`
`       login: true`

what oauth generates

`access:`
`    site.login: '1'`

problem is not weather there is true or '1' but in the formatting which leads to setting rights manually.
@flaviocopes

**Comment by flaviocopes** [comment] 2016-02-04 11:43
```
access:
  site.login: '1'
```

and 

```
access:
  site:
    login: true
```

are equivalent.

I just tested, things seem to be fine. After creating the user, the user is logged in.

Please indent properly as from what you write I can't determine if the spacing is correct. Use triple backticks.

**Comment by flaviocopes** [comment] 2016-02-04 11:54
Double-checked. Legitimate issue. Was trying some changes but the user access was cached so I could not reproduce it.

**Comment by Ricoom** [comment] 2016-02-04 12:01
page header
```
title: secure
slug: secure
access:
    site.right: true
```
plugin settings 
[http://imgur.com/dO9veE8](url)

Oauth auto generated user

```
email: some@email.com
lang: ''
access:
  site.login: '1'
  site.right: '1'
authenticated: false
hashed_password: $SOMECOOLHASH
```

command line generated user

```
email: some@email.com
access:
  admin:
    login: true
    super: true
  site:
    login: true
fullname: 'Full Name'
title: Developer
state: enabled
hashed_password: $SOMECOOLHASH
```
if I add the permission 'right' to the command line generated file in that format it works 

```
email: some@email.com
access:
  admin:
    login: true
    super: true
  site:
    login: true
    right: true
fullname: 'Full Name'
title: Developer
state: enabled
hashed_password: $SOMECOOLHASH
```

Oauth generated version does not work

**Comment by flaviocopes** [comment] 2016-02-04 12:46
Should be fixed now. Can you check too?

**Comment by Ricoom** [comment] 2016-02-05 07:20
I feel like the issue is more likely in faulty user interface 
[http://imgur.com/a/DmIhx](url)
It starts off having an extra field for like first part and option to add more but if you want to add new first part one it starts giving off a a different type of fields all togather.. If you remove first type of fields all togather theres no way getting them back.

**Comment by flaviocopes** [comment] 2016-02-10 11:16
Fixed in the next release

**Closed by flaviocopes** 2016-02-10 11:16 UTC
Labels: bug
